package schemaorg

const (
	TypeAboutPage           = "AboutPage"
	TypeAction              = "Action"
	TypeAnswer              = "Answer"
	TypeAudience            = "Audience"
	TypeBusinessAudience    = "BusinessAudience"
	TypeCheckoutPage        = "CheckoutPage"
	TypeCollectionPage      = "CollectionPage"
	TypeComment             = "Comment"
	TypeContactPage         = "ContactPage"
	TypeCorrectionComment   = "CorrectionComment"
	TypeComputerLanguage    = "ComputerLanguage"
	TypeEducationalAudience = "EducationalAudience"
	TypeFAQPage             = "FAQPage"
	TypeFlight              = "Flight"
	TypeIntangible          = "Intangible"
	TypeItemPage            = "ItemPage"
	TypeMedicalAudience     = "MedicalAudiencee"
	TypeMedicalWebPage      = "MedicalWebPage"
	TypeParentAudience      = "ParentAudience"
	TypePatient             = "Patient"
	TypePeopleAudience      = "PeopleAudience"
	TypePerson              = "Person"
	TypeProfilePage         = "ProfilePage"
	TypeQAPage              = "QAPage"
	TypeQuestion            = "Question"
	TypeRealEstateListing   = "RealEstateListing"
	TypeResearcher          = "Researcher"
	TypeSearchResultsPage   = "SearchResultsPage"
	TypeVirtualLocation     = "VirtualLocation"
	TypeWebPage             = "WebPage"
)
